site_name: FluxCLI
site_url: https://shaharband.github.io/fluxcli/
site_description: Lightweight, CLI-first framework for DAG-based workfluxs
repo_url: https://github.com/ShaharBand/fluxcli
repo_name: ShaharBand/fluxcli
docs_dir: docs

theme:
  name: material
  logo: imgs/logo.jpg
  favicon: imgs/logo.jpg
  
  features:
    - navigation.expand
    - navigation.tabs       
    - navigation.top         
    - content.code.annotate
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.mark
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.inlinehilite

nav:
  - FluxCLI:
      - Overview: index.md
  - Features: features.md
  - Learn:
      - Getting started: getting-started.md
      - Core concepts: concepts.md
      - Demo: demo.md
  - Reference:
      - CLI flags: cli-flags.md
      - Exceptions: exceptions.md
  - People:
      - Maintainers: people.md
  - Resources:
      - Resources: resources.md
