site_name: Fluxly
site_url: https://shaharband.github.io/fluxly/
site_description: Framework for portable, self-contained DAG workflows, decoupled from orchestration.
repo_url: https://github.com/ShaharBand/fluxly
repo_name: ShaharBand/fluxly
docs_dir: docs

theme:
  name: material
  logo: imgs/logo.png
  favicon: imgs/logo.png
  
  features:
    - navigation.expand
    - navigation.tabs       
    - navigation.top         
    - content.code.annotate
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.mark
  - pymdownx.betterem
  - pymdownx.highlight
  - pymdownx.inlinehilite

nav:
  - Fluxly: index.md
  - Features: features.md
  - Learn:
      - Getting started: getting-started.md
      - Core concepts: concepts.md
      - Demo: demo.md
  - Reference:
      - Input flags: input-flags.md
      - Exceptions: exceptions.md
  - People:
      - Maintainers: people.md
  - Resources:
      - Resources: resources.md
